# Generated by Django 3.0.7 on 2021-06-02 11:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=50, unique=True, verbose_name='ビール名')),
                ('maker', models.CharField(blank=True, max_length=100, null=True, verbose_name='製造会社')),
                ('origin_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='生産地')),
                ('alcohol_degree', models.FloatField(blank=True, max_length=2, null=True, verbose_name='アルコール度数')),
                ('type', models.CharField(blank=True, choices=[('エール', 'エール'), ('ラガー', 'ラガー')], default='エール', max_length=10, null=True, verbose_name='種類')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='値段')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='内容量')),
                ('features', models.TextField(blank=True, null=True, verbose_name='特徴')),
                ('url', models.URLField(blank=True, null=True, verbose_name='公式サイト')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='総合評価')),
                ('taste_kire', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='キレ')),
                ('taste_sannmi', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='酸味')),
                ('taste_nigami', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='苦味')),
                ('taste_amami', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='甘味')),
                ('taste_koku', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='コク')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Beer', verbose_name='ビール')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Favo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Beer', verbose_name='ビール')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, unique=True, verbose_name='ビール名')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Review', verbose_name='レビュー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
